{"version":1,"ops":[{"type":1,"author":{"id":"56b030459ff5c3e63b58d71e1bed10897e6a7686"},"timestamp":1256890223,"metadata":{"github-id":"MDU6SXNzdWUyODQ4NjA3","github-url":"https://github.com/parrot/parrot/issues/402","origin":"github"},"title":"Pg NCI Test Makes Unportable Connection","message":"t/library/pg.t fails pretty miserably on this line:\n\ncon = cl.'connectdb'('') # assume table = user is present\n\nI have PostgreSQL installed, but this assumption doesn't work for me. I've \nchecked in a skip for the remaining tests in this case, as there's no point \nin running them. (They cause NCI assertion failures, as the NULL connection \nisn't what NCI expects to pass to the Pg functions.)\n\nThis test needs another approach to run on multiple platforms successfully. \nSetting an environment variable for user name and password might work better.\n\n-- c\n\nOriginally http://trac.parrot.org/parrot/ticket/1162","files":null}]}