{"version":1,"ops":[{"type":1,"author":{"id":"531f213490a150dd157bb329db78197c5d1f681e"},"timestamp":1273766263,"metadata":{"github-id":"MDU6SXNzdWUyODQ4NjMx","github-url":"https://github.com/parrot/parrot/issues/424","origin":"github"},"title":"Exception handler throwing exception in NQP-rx causes segfault","message":"{ pir::die(\"\"); CATCH { pir::die(\"\"); } }\n\nThe NQP-rx generated exception handler does not call pop_eh in the handler path, which apparently it should, according to bacek.\n\nOriginally http://trac.parrot.org/parrot/ticket/1631","files":null}]}